version: '3'

services:
  
  mysql:
    image: mysql:5.7.16
    container_name: mysql
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nginxdb
      - MYSQL_ROOT_PASSWORD=pas123
    networks: 
      - fullCycleNet
      
  ngnix:
    build:
      context: ./ngnix
    image: ngnix-dev
    container_name: ngnix
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - fullCycleNet
  
  node:
    build: 
      context: ./node
    image: node-dev
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s node index.js
    depends_on:
      - mysql
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    networks:
     - fullCycleNet 

networks: 
  fullCycleNet:
    driver: bridge